//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TimbradoNomina.WSCFDI {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="timbrarCFDIBinding", Namespace="urn:respuestaTimbrado")]
    public partial class timbrarCFDI : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CalltimbrarCFDIOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public timbrarCFDI() {
            this.Url = global::TimbradoNomina.Properties.Settings.Default.TimbradoNomina_WSCFDI_timbrarCFDI;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CalltimbrarCFDICompletedEventHandler CalltimbrarCFDICompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://comprobantes-fiscales.com/service/timbraCFDI.php/timbrarCFDI", RequestNamespace="urn:respuestaTimbrado", ResponseNamespace="urn:respuestaTimbrado")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public respuestaTimbrado CalltimbrarCFDI(string suscriptorRFC, string agenteTI, string documentoXML) {
            object[] results = this.Invoke("CalltimbrarCFDI", new object[] {
                        suscriptorRFC,
                        agenteTI,
                        documentoXML});
            return ((respuestaTimbrado)(results[0]));
        }
        
        /// <remarks/>
        public void CalltimbrarCFDIAsync(string suscriptorRFC, string agenteTI, string documentoXML) {
            this.CalltimbrarCFDIAsync(suscriptorRFC, agenteTI, documentoXML, null);
        }
        
        /// <remarks/>
        public void CalltimbrarCFDIAsync(string suscriptorRFC, string agenteTI, string documentoXML, object userState) {
            if ((this.CalltimbrarCFDIOperationCompleted == null)) {
                this.CalltimbrarCFDIOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCalltimbrarCFDIOperationCompleted);
            }
            this.InvokeAsync("CalltimbrarCFDI", new object[] {
                        suscriptorRFC,
                        agenteTI,
                        documentoXML}, this.CalltimbrarCFDIOperationCompleted, userState);
        }
        
        private void OnCalltimbrarCFDIOperationCompleted(object arg) {
            if ((this.CalltimbrarCFDICompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CalltimbrarCFDICompleted(this, new CalltimbrarCFDICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:respuestaTimbrado")]
    public partial class respuestaTimbrado {
        
        private string documentoTimbradoField;
        
        private string codigoResultadoField;
        
        private string codigoDescripcionField;
        
        /// <comentarios/>
        public string documentoTimbrado {
            get {
                return this.documentoTimbradoField;
            }
            set {
                this.documentoTimbradoField = value;
            }
        }
        
        /// <comentarios/>
        public string codigoResultado {
            get {
                return this.codigoResultadoField;
            }
            set {
                this.codigoResultadoField = value;
            }
        }
        
        /// <comentarios/>
        public string codigoDescripcion {
            get {
                return this.codigoDescripcionField;
            }
            set {
                this.codigoDescripcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void CalltimbrarCFDICompletedEventHandler(object sender, CalltimbrarCFDICompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CalltimbrarCFDICompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CalltimbrarCFDICompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public respuestaTimbrado Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((respuestaTimbrado)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591